shuup_cielo/urls.py
# -*- coding: utf-8 -*-
# This file is part of Shuup Cielo.
#
# Copyright (c) 2016, Rockho Team. All rights reserved.
# Author: Christian Hess
#
# This source code is licensed under the AGPLv3 license found in the
# LICENSE file in the root directory of this source tree.

from django.conf.urls import patterns, url
from django.views.decorators.csrf import csrf_exempt

from shuup_cielo.views import GetInstallmentsOptionsView, TransactionReturnView, TransactionView

urlpatterns = patterns(
    '',
    url(r'^checkout/installment/$', GetInstallmentsOptionsView.as_view(),
        name='cielo_get_installment_options'),

    url(r'^checkout/transaction/$', TransactionView.as_view(),
        name='cielo_make_transaction'),

    url(r'^checkout/return/(?P<cielo_order_pk>\d+)/$',
        csrf_exempt(TransactionReturnView.as_view()),
        name='cielo_transaction_return')
)

shuup_cielo/models.py
# -*- coding: utf-8 -*-
# This file is part of Shuup Cielo.
#
# Copyright (c) 2016, Rockho Team. All rights reserved.
# Author: Christian Hess
#
# This source code is licensed under the AGPLv3 license found in the
# LICENSE file in the root directory of this source tree.
from __future__ import unicode_literals

from decimal import Decimal
import logging

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.http.response import HttpResponseRedirect
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from enumfields import EnumIntegerField
import iso8601

from cielo_webservice.models import Comercial
from cielo_webservice.request import CieloRequest
from shuup.core.fields import MoneyValueField
from shuup.core.models import PaymentProcessor, ServiceChoice
from shuup.core.models._service_base import ServiceBehaviorComponent, ServiceCost
from shuup.core.models._shops import Shop
from shuup.utils.analog import LogEntryKind
from shuup.utils.excs import Problem
from shuup.utils.properties import MoneyProperty
from shuup_cielo.constants import (
    CIELO_AUTHORIZATION_TYPE_CHOICES, CIELO_DECIMAL_PRECISION, CIELO_PRODUCT_CHOICES,
    CIELO_SERVICE_CREDIT, CIELO_SERVICE_DEBIT, CieloAuthorizationType, CieloTransactionStatus,
    INTEREST_TYPE_CHOICES, InterestType
)
from shuup_cielo.objects import CIELO_ORDER_TRANSACTION_ID_KEY, CIELO_TRANSACTION_ID_KEY
from shuup_cielo.utils import decimal_to_int_cents, InstallmentCalculator, safe_int

logger = logging.getLogger(__name__)


class CieloPaymentProcessor(PaymentProcessor):
    '''
    Processador de pagamento Cielo
    '''

    class Meta:
        verbose_name = _('Cielo')
        verbose_name_plural = _('Cielo')

    def get_service_choices(self):
        return [
            ServiceChoice(CIELO_SERVICE_CREDIT, _('Credit card')),
            ServiceChoice(CIELO_SERVICE_DEBIT, _('Debit card')),
        ]

    def create_service(self, choice_identifier, **kwargs):
        service = super(CieloPaymentProcessor, self).create_service(choice_identifier, **kwargs)
        service.behavior_components.add(CieloInstallmentInterestBehaviorComponent.objects.create())
        return service

    def get_payment_process_response(self, service, order, urls):
        """
        Get payment process response for given order.

        :type service: shuup.core.models.PaymentMethod
        :type order: shuup.core.models.Order
        :type urls: PaymentUrls
        :rtype: django.http.HttpResponse|None
        """

        cielo_transaction = CieloTransaction.objects.filter(
            pk=order.payment_data.get(CIELO_TRANSACTION_ID_KEY)
        ).first()

        cielo_order = CieloOrderTransaction.objects.filter(
            pk=order.payment_data.get(CIELO_ORDER_TRANSACTION_ID_KEY)
        ).first()

        if not cielo_order or not cielo_transaction:
            order.set_canceled()
            order.add_log_entry(_('No payment identified.'), kind=LogEntryKind.ERROR)
            raise Problem(_('No payment identified.'), title=_('Order cancelled'))

        # faz as amarrações
        cielo_order.order = order
        cielo_order.save()

        return HttpResponseRedirect(urls.return_url)

    def process_payment_return_request(self, service, order, request):
        # limpa os dados da sessão
        request.cielo.clear()


@python_2_unicode_compatible
class CieloOrderTransaction(models.Model):
    """
    A sequence that is used as a order number before the real Order is created
    This is necessary because the transactions is made before the order is placed.
    """
    order = models.ForeignKey('shuup.Order',
                              related_name='cielo_transactions',
                              on_delete=models.CASCADE,
                              verbose_name=_('Order'),
                              null=True, default=None)

    class Meta:
        verbose_name = _('Cielo pre-order transaction')
        verbose_name_plural = _('Cielo pre-order transactions')

    def __str__(self):
        return "CieloOrder {0} for order ID {1}".format(self.id, self.order_id)


@python_2_unicode_compatible
class CieloTransaction(models.Model):
    TIMEOUT_SECONDS = 5

    shop = models.ForeignKey(Shop, verbose_name=_("shop"))
    order_transaction = models.OneToOneField(CieloOrderTransaction,
                                             related_name="transaction",
                                             verbose_name=_("Cielo Order"))
    tid = models.CharField(_('Transaction ID'), max_length=50)
    status = EnumIntegerField(CieloTransactionStatus,
                              verbose_name=_('Transaction status'),
                              default=CieloTransactionStatus.NotCreated,
                              blank=True)
    creation_date = models.DateTimeField(_('Creation date'), auto_now_add=True)
    last_update = models.DateTimeField(_('Last update'), auto_now=True)

    cc_holder = models.CharField(_('Card holder'), max_length=50)
    cc_brand = models.CharField(_('Card brand'), max_length=30)
    installments = models.PositiveSmallIntegerField(_('Installments'), default=1)
    cc_product = models.CharField(_('Product'), max_length=30, choices=CIELO_PRODUCT_CHOICES)

    total = MoneyProperty('total_value', 'order_transaction.order.currency')
    total_captured = MoneyProperty('total_captured_value', 'order_transaction.order.currency')
    total_reversed = MoneyProperty('total_reversed_value', 'order_transaction.order.currency')
    intereset = MoneyProperty('interest_value', 'order_transaction.order.currency')

    total_value = MoneyValueField(editable=False, verbose_name=_('transaction total'), default=0)
    total_captured_value = MoneyValueField(editable=True, verbose_name=_('total captured'), default=0)
    total_reversed_value = MoneyValueField(editable=True, verbose_name=_('total reversed'), default=0)
    interest_value = MoneyValueField(editable=False, verbose_name=_('interest amount'), default=0)

    authorization_lr = models.CharField(_('Authorization LR code'), max_length=2, blank=True)
    authorization_nsu = models.CharField(_('Authorization NSU'), max_length=50, blank=True, null=True)
    authorization_date = models.DateTimeField(_('Authorization date'), null=True, blank=True)

    authentication_eci = models.SmallIntegerField(_('ECI security level'), null=True, default=0)
    authentication_date = models.DateTimeField(_('Authentication date'), null=True, blank=True)

    international = models.BooleanField(_('International transaction'), default=False)

    class Meta:
        verbose_name = _('Cielo 1.5 transaction')
        verbose_name_plural = _('Cielo 1.5 transactions')

    def __str__(self):
        return "CieloTransaction TID={0}".format(self.tid)

    def _get_comercial(self):
        cielo_config = self.shop.cielo_config
        return Comercial(numero=safe_int(cielo_config.ec_num), chave=cielo_config.ec_key)

    def _get_cielo_request(self):
        return CieloRequest(sandbox=self.shop.cielo_config.sandbox)

    def refresh(self):
        '''
        Updates this transaction info with Cielo server

        :return: wheter the synchronization was successful
        '''

        # consuta a transação
        cielo_request = self._get_cielo_request()

        try:
            response_transaction = cielo_request.consultar(tid=self.tid,
                                                           comercial=self._get_comercial())
            self._update_from_transaction(response_transaction)
            return True

        except:
            logger.exception(_('Fail to update Cielo transation info'))

        return False

    def _update_from_transaction(self, response_transaction):
        if response_transaction.status:
            self.status = response_transaction.status

        if response_transaction.autorizacao:
            self.authorization_lr = response_transaction.autorizacao.lr
            self.authorization_nsu = response_transaction.autorizacao.nsu
            self.authorization_date = iso8601.parse_date(response_transaction.autorizacao.data_hora)
            self.international = (response_transaction.autorizacao.lr == "11")

        if response_transaction.autenticacao:
            self.authentication_eci = response_transaction.autenticacao.eci
            self.authentication_date = iso8601.parse_date(response_transaction.autenticacao.data_hora)

        if response_transaction.captura:
            self.total_captured_value = Decimal(response_transaction.captura.valor / 100.0)

        if response_transaction.cancelamento:
            self.total_reversed_value = Decimal(response_transaction.cancelamento.valor / 100.0)

        self.save()

    def capture(self, amount):
        '''
        Captures a total or partial amout of this transaction
        :type: amount: decimal.Decimal
        '''

        cielo_request = self._get_cielo_request()
        response_transaction = cielo_request.capturar(tid=self.tid,
                                                      comercial=self._get_comercial(),
                                                      valor=decimal_to_int_cents(amount))
        self._update_from_transaction(response_transaction)

    def safe_cancel(self, amount):
        """
        Safe transaction cancel (try, catch enclosed)
        :return: success or not
        :rtype: bool
        """
        try:
            self.cancel(amount)
            return True
        except:
            logger.exception(_("Failed to cancel transaction {0}").format(self.tid))
            return False

    def cancel(self, amount):
        '''
        Cancel a total or partial amout of this transaction
        :type: amount: decimal.Decimal
        '''
        cielo_request = self._get_cielo_request()
        response_transaction = cielo_request.cancelar(tid=self.tid,

shuup_cielo/templates/cielo/admin/config_edit.jinja
{% extends "shuup/admin/base.jinja" %}
{% from "shuup/admin/macros/general.jinja" import single_section_form with context %}
{% block content %}
    {{ single_section_form("config_form", form) }}
{% endblock %}

shuup_cielo/templates/cielo/admin/dashboard.jinja
{% extends "shuup/admin/base.jinja" %}

{% block content %}
<p>{% trans %}This version contains no information about transactions yet. Improvements are currently being developed..{% endtrans %}</p>

<p><small>{% trans %}Version:{% endtrans %} <strong>{{ VERSION }}</strong></small></p>
{% endblock %}

shuup_cielo/templates/cielo/admin/order_section.jinja
<h4>{% trans %}Transactions{% endtrans %}</h4>

<hr>

{% set CieloTransactionStatus=cielo.CieloTransactionStatus %}
{% for transaction in cielo.transactions %}
    <dl class="dl-horizontal">
        <div id="transaction-{{ transaction.pk }}">
            {% include "cielo/admin/order_section_transaction_detail.jinja" with context %}
        </div>
    </dl>

    <hr>
{% endfor %}

shuup_cielo/templates/cielo/admin/order_section_extra_js.jinja
<script>
    function refresh(pk){
        $.ajax({
            type: "POST",
            url: "{{ url('shuup_admin:cielo.transaction-refresh') }}",
            data: {
                "id": pk,
                "csrfmiddlewaretoken": '{{ csrf_token }}',
            },
            success: function(data){
                $('#transaction-'+pk).html(data);
            },
            error: function(){
                alert("{% trans %}There was an error refreshing the transaction.{% endtrans %}")
            },
        });
    }

    function capture(pk){
        if(confirm("{{ _("Are you sure do you want to CAPTURE this transaction?") }}")){
            $.ajax({
                type: "POST",
                url: "{{ url('shuup_admin:cielo.transaction-capture') }}",
                data: {
                    "id": pk,
                    "amount": $('#capture-'+pk+'-amount').val(),
                    "csrfmiddlewaretoken": '{{ csrf_token }}',
                },
                success: function(data){
                    $('#transaction-'+pk).html(data);
                },
                error: function(data){
                    alert("{% trans %}There was an error capturing the transaction.{% endtrans %}: " + data.responseText)
                },
            });
        }
    }

    function cancel(pk){
        if(confirm("{{ _("Are you sure do you want to CANCEL this transaction?") }}")){
            $.ajax({
                type: "POST",
                url: "{{ url('shuup_admin:cielo.transaction-cancel') }}",
                data: {
                    "id": pk,
                    "amount": $('#cancel-'+pk+'-amount').val(),
                    "csrfmiddlewaretoken": '{{ csrf_token }}',
                },
                success: function(data){
                    $('#transaction-'+pk).html(data);
                },
                error: function(data){
                    alert("{% trans %}There was an error canceling the transaction.{% endtrans %}: " + data.responseText)
                },
            });
        }
    }
</script>

shuup_cielo/templates/cielo/admin/order_section_transaction_detail.jinja
{% macro cielo_info_row(header, value, url=None, class="", content_class="") %}
    {% if value is defined and value is not none and value != "" %}
        <dt>{{ header }}</dt>
        <dd{% if class %} class="{{ class }}"{% endif %}>
            {%- if url %}<a href="{{ url }}">{% endif -%}
            <span {% if content_class %}class="{{ content_class }}"{% endif %}>{{ value }}</span>
            {%- if url %}</a>{% endif -%}
        </dd>
        {% if caller %}
            <dd>{{ caller() }}</dd>
        {% endif %}
    {% endif %}
{% endmacro %}


{{ cielo_info_row(_("TID"), transaction.tid) }}
{{ cielo_info_row(_("Create date"), transaction.creation_date|datetime) }}

{# aprovada #}
{% if transaction.status == CieloTransactionStatus.Authorized %}
{{ cielo_info_row(_("Status"), transaction.status, content_class="label label-info") }}

{# negada #}
{% elif transaction.status == CieloTransactionStatus.NotAuthorized %}
{{ cielo_info_row(_("Status"), transaction.status, content_class="label label-warning") }}

{# capturada #}
{% elif transaction.status == CieloTransactionStatus.Captured %}
{{ cielo_info_row(_("Status"), transaction.status, content_class="label label-success") }}

{# cancelada #}
{% elif transaction.status in (CieloTransactionStatus.Cancelled, CieloTransactionStatus.Cancelling) %}
{{ cielo_info_row(_("Status"), transaction.status, content_class="label label-danger") }}

{% else %}
{{ cielo_info_row(_("Status"), transaction.status, content_class="label label-default") }}

{% endif %}

{{ cielo_info_row(_("Last update"), transaction.last_update|datetime) }}

{{ cielo_info_row(_("Holder"), transaction.cc_holder, content_class="text-uppercase text-info") }}
{{ cielo_info_row(_("Card brand"), transaction.cc_brand, content_class="text-uppercase label label-info") }}
{{ cielo_info_row(_("Product"), transaction.get_cc_product_display(), content_class="text-uppercase text-info") }}
{{ cielo_info_row(_("Installments"), transaction.installments|string + 'x ' + (transaction.total / transaction.installments)|money, content_class="text-info") }}

{{ cielo_info_row(_("Total"), transaction.total|money, content_class="text-primary") }}
{{ cielo_info_row(_("Total captured"), transaction.total_captured|money, content_class="text-success") }}
{{ cielo_info_row(_("Total canceled"), transaction.total_reversed|money, content_class="text-danger") }}

{{ cielo_info_row(_("Authorization LR"), transaction.authorization_lr) }}
{{ cielo_info_row(_("Authorization NSU"), transaction.authorization_nsu) }}
{{ cielo_info_row(_("International?"), _("yes") if transaction.international else _("no")) }}

{% if transaction.authorization_date %}
{{ cielo_info_row(_("Authorization date"), transaction.authorization_date|datetime) }}
{% endif %}

{{ cielo_info_row(_("Authentication ECI"), transaction.authentication_eci, content_class="label label-primary") }}

{% if transaction.authentication_date %}
{{ cielo_info_row(_("Authentication date"), transaction.authentication_date|datetime) }}
{% endif %}

<dd>
    <button class="btn btn-info" id="refresh-{{ transaction.id }}" onclick="refresh({{ transaction.id }});">{% trans %}Refresh{% endtrans %}</button>
</dd>

<dd>
    <input type="text" name="capture-{{ transaction.id }}-amount" value="{{ (transaction.total_value-transaction.total_captured_value)|round(2) }}">
    <button class="btn btn-success" id="capture-{{ transaction.id }}" onclick="capture({{ transaction.id }});">{% trans %}Capture{% endtrans %}</button>
</dd>

<dd>
    <input type="text" name="cancel-{{ transaction.id }}-amount" value="{{ (transaction.total_value-transaction.total_reversed_value)|round(2) }}">
    <button class="btn btn-danger" id="cancel-{{ transaction.id }}" onclick="cancel({{ transaction.id }});">{% trans %}Cancel{% endtrans %}</button>
</dd>